//@ui5-bundle app/app/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"app/app/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","app/app/model/models"],function(e,t,i){"use strict";return e.extend("app.app.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"app/app/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("app.app.controller.App",{onInit:function(){}})});
},
	"app/app/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("app.app.controller.BaseController",{getRouter:function(){return this.getOwnerComponent().getRouter()},getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)}})});
},
	"app/app/controller/Gerenciar.controller.js":function(){sap.ui.define(["./BaseController","sap/ui/model/json/JSONModel"],function(e,n){"use strict";return e.extend("app.app.controller.Menu",{onInit:async function(){var e=this;await $.ajax({url:"/main/Employees?$expand=department",method:"GET",success(t){var o=t.value.length;var a=t.value.reduce((e,n)=>{if(n.department.name in e){e[n.department.name]++}else{e[n.department.name]=1}return e},{});a.total=o;console.log("sucesso");e.getView().setModel(new n(a),"Total")},error(){console.log("erro: hello")}})},onNavGerenciar:function(){this.getRouter().navTo("Gerenciar")},onNavRelatorio:function(){this.getRouter().navTo("Relatorio")},onNavListar:function(){this.getRouter().navTo("Listar")}})});
},
	"app/app/controller/Listar.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("app.app.controller.Listar",{onInit:function(){}})});
},
	"app/app/controller/Menu.controller.js":function(){sap.ui.define(["./BaseController"],function(e){"use strict";return e.extend("app.app.controller.Menu",{onInit:function(){},onNavGerenciar:function(){this.getRouter().navTo("Gerenciar")},onNavRelatorio:function(){this.getRouter().navTo("Relatorio")},onNavTeste:function(){this.getRouter().navTo("Teste")}})});
},
	"app/app/controller/Relatorio.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("app.app.controller.Relatorio",{onInit:function(){}})});
},
	"app/app/controller/Teste.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("app.app.controller.Teste",{onInit:function(){}})});
},
	"app/app/i18n/i18n.properties":'title=Title\nappTitle=App\nappDescription=App Description\n',
	"app/app/manifest.json":'{"_version":"1.32.0","sap.app":{"id":"app.app","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","ach":"ach"},"sap.ui":{"technology":"UI5","icons":{"icon":"sap-icon://task","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"app.app.view.App","type":"XML","async":true,"id":"App"},"dependencies":{"minUI5Version":"1.66.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"app.app.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"app.app.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteApp","pattern":"RouteApp","target":["TargetApp"]},{"name":"Menu","pattern":"","target":["Menu","Relatorio"]},{"name":"Relatorio","pattern":"Relatorio","target":["Menu","Relatorio"]},{"name":"Gerenciar","pattern":"Gerenciar","target":["Menu","Gerenciar"]},{"name":"Listar","pattern":"Listar","target":["Menu","Listar"]},{"name":"Teste","pattern":"Teste","target":["Menu","Teste"]}],"targets":{"Menu":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"menu","viewName":"Menu","controlAggregation":"masterPages"},"TargetApp":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"App","viewName":"App"},"Relatorio":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"relatorio","viewName":"Relatorio","controlAggregation":"detailPages"},"Gerenciar":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"gerenciar","viewName":"Gerenciar","controlAggregation":"detailPages"},"Listar":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"listar","viewName":"Listar","controlAggregation":"detailPages"},"Teste":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"teste","viewName":"Teste","controlAggregation":"detailPages"}}}}}',
	"app/app/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"app/app/view/App.view.xml":'<mvc:View\n    controllerName="app.app.controller.App"\n    xmlns:mvc="sap.ui.core.mvc"\n    displayBlock="true"\n    xmlns="sap.m"\n><SplitApp id="app"></SplitApp></mvc:View>\n',
	"app/app/view/Gerenciar.view.xml":'<mvc:View\r\n    controllerName="app.app.controller.Gerenciar"\r\n    xmlns:mvc="sap.ui.core.mvc"\r\n    displayBlock="true"\r\n    xmlns="sap.m"\r\n><Page showHeader="true" title="Gerenciar Equipes" titleAlignment="Center"><content><Title text="Totais:" level="H3" class="sapUiTinyMarginBegin sapUiTinyMarginTop " /><ToolbarSpacer ></ToolbarSpacer><GenericTag text="Funcionários"  design="StatusIconHidden" status="Warning"  class=" sapUiTinyMarginBegin sapUiSmallMarginBottom"><ObjectNumber state="None" emphasized="true" number="200"  /></GenericTag><GenericTag text="Recursos Humanos"  design="StatusIconHidden" status="Warning"  class=" sapUiTinyMarginBegin sapUiSmallMarginBottom"><ObjectNumber state="None" emphasized="true" number="30"  /></GenericTag><GenericTag text="Financeiro"  design="StatusIconHidden" status="Warning"  class=" sapUiTinyMarginBegin sapUiSmallMarginBottom"><ObjectNumber state="None" emphasized="true" number="28"  /></GenericTag><GenericTag text="Projetos"  design="StatusIconHidden" status="Warning"  class=" sapUiTinyMarginBegin sapUiSmallMarginBottom"><ObjectNumber state="None" emphasized="true" number="142"  /></GenericTag><ToolbarSpacer ></ToolbarSpacer><Title text="Escolha a porcentagem:" level="H3" class="sapUiTinyMarginBegin sapUiTinyMarginTop " /><ToolbarSpacer ></ToolbarSpacer><Slider value="50" width="90%" min="0" max="100" showAdvancedTooltip="true" showHandleTooltip="false" class="sapUiMediumMarginBottom" /><ToolbarSpacer ></ToolbarSpacer><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="Funcionarios" subheader="Recursos Humanos" press="press"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="10"  withMargin="false" /></TileContent></GenericTile><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="Funcionarios" subheader="Administração" press="press"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="12" withMargin="false" /></TileContent></GenericTile><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="Funcionarios" subheader="Desenvolvimento" press="press"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="25" withMargin="false" /></TileContent></GenericTile><ToolbarSpacer ></ToolbarSpacer><VBox><items><StandardListItem  title = "Listar" press="onNavRelatorio" type = "Navigation" icon = "sap-icon://activity-individual"/></items></VBox></content></Page></mvc:View>\r\n',
	"app/app/view/Listar.view.xml":'<mvc:View xmlns:control="sap.gantt.control"\r\n    controllerName="app.app.controller.Menu"\r\n    xmlns:mvc="sap.ui.core.mvc"\r\n    displayBlock="true"\r\n    xmlns="sap.m"\r\n><Page showHeader="true" title="Listar" titleAlignment="Center"><content><Table mode="Delete" id="tablePlataformas" delete="onExcluir" items="{path: \'Plataformas>/\'}"><headerToolbar><OverflowToolbar ><content><Title text="Funcionários" level="H2" /><ToolbarSpacer ></ToolbarSpacer><SearchField placeholder="Digite o CPF do funcionário" width="50%" liveChange="onSearch" ></SearchField></content></OverflowToolbar></headerToolbar><columns><Column demandPopin="true" minScreenWidth="Desktop"><Label wrapping="true" text="CPF" design="Bold"></Label></Column><Column demandPopin="true" minScreenWidth="Desktop"><Label wrapping="true" text="Nome" design="Bold"></Label></Column><Column demandPopin="true" minScreenWidth="Desktop"><Label wrapping="true" text="Idade" design="Bold"></Label></Column><Column demandPopin="true" minScreenWidth="Desktop"><Label wrapping="true" text="Pontos" design="Bold"></Label></Column></columns><items><ColumnListItem type="Detail" detailPress="onNavEditarPlataformas"><cells><Text text="{Plataformas>CPF}"></Text><Text text="{Plataformas>nome}"></Text><Text text="{Plataformas>idade}"></Text><Text text="{Plataformas>Pontos}"></Text></cells></ColumnListItem></items></Table></content></Page></mvc:View>',
	"app/app/view/Menu.view.xml":'<mvc:View\r\n    controllerName="app.app.controller.Menu"\r\n    xmlns:mvc="sap.ui.core.mvc"\r\n    displayBlock="true"\r\n    xmlns="sap.m"\r\n><Page showHeader="true" title="Menu" titleAlignment="Center"><content ><VBox width="100%" ><Image src="images/logo_tr.png" width="100%" height="100%" /><List ><items><StandardListItem  title = "Relátorios" press="onNavRelatorio" type = "Navigation" icon = "sap-icon://manager-insight"/></items><items><StandardListItem title = "Gerenciar Equipes" press="onNavGerenciar" type = "Navigation" icon = "sap-icon://manager"/></items><items><StandardListItem title = "Teste" press="onNavTeste"  type = "Navigation" icon = "sap-icon://overview-chart"/></items></List></VBox></content></Page></mvc:View>\r\n',
	"app/app/view/Relatorio.view.xml":'<mvc:View\r\n    controllerName="app.app.controller.Relatorio"\r\n    xmlns:mvc="sap.ui.core.mvc"\r\n    displayBlock="true"\r\n    xmlns="sap.m"\r\n><Page showHeader="true" title="Relátorios" titleAlignment="Center"><content><Title text="Valores Gerais:" level="H3" class="sapUiTinyMarginBegin sapUiTinyMarginTop " /><ToolbarSpacer ></ToolbarSpacer><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop " header="Funcionarios"  press="press" width="25%"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="10"  withMargin="false" /></TileContent></GenericTile><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="Funcionarios em home office"  press="press"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="12" withMargin="false" /></TileContent></GenericTile><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="Funcionarios Contaminados "  press="press"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="25" withMargin="false" /></TileContent></GenericTile><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="Casos ativos "  press="press"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="25" withMargin="false" /></TileContent></GenericTile><ToolbarSpacer ></ToolbarSpacer><Title text="Casos por setor:" level="H3" class="sapUiTinyMarginBegin sapUiTinyMarginTop " /><ToolbarSpacer ></ToolbarSpacer><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop " header="Recursos Humanos"  press="press" width="25%"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="10"  withMargin="false" /></TileContent></GenericTile><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="Financeiro"  press="press"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="12" withMargin="false" /></TileContent></GenericTile><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="Projetos "  press="press"><TileContent unit="Unit" footer="Footer Text"><NumericContent value="25" withMargin="false" /></TileContent></GenericTile></content></Page></mvc:View>',
	"app/app/view/Teste.view.xml":'<mvc:View xmlns:unified="sap.ui.unified"\r\n    controllerName="app.app.controller.Teste"\r\n    xmlns:mvc="sap.ui.core.mvc"\r\n    displayBlock="true"\r\n    xmlns="sap.m"\r\n    xmlns:tnt="sap.tnt"\r\n\theight="100%"\r\n><Page showHeader="true" title="Teste" titleAlignment="Center"><content><PlanningCalendar \r\n                id="PC1"\r\n\t\t\t\tstartDate="{path: \'/startDate\'}"\r\n\t\t\t\trows="{path: \'/people\'}"\r\n\t\t\t\tappointmentsVisualization="Filled"\r\n\t\t\t\tappointmentSelect="handleAppointmentSelect"\r\n\t\t\t\tshowEmptyIntervalHeaders="false"\r\n\t\t\t\tintervalSelect="handleAppointmentAddWithContext" ><rows><PlanningCalendarRow \t\r\n                        icon="{pic}"\r\n\t\t\t\t\t\ttitle="{name}"\r\n\t\t\t\t\t\ttext="{role}"\r\n\t\t\t\t\t\tappointments="{path : \'appointments\', templateShareable: false}"\r\n\t\t\t\t\t\tintervalHeaders="{path: \'headers\', templateShareable: false}"><appointments><unified:CalendarAppointment\r\n                                startDate="{start}"\r\n\t\t\t\t\t\t\t\tendDate="{end}"\r\n\t\t\t\t\t\t\t\ticon="{pic}"\r\n\t\t\t\t\t\t\t\ttitle="{title}"\r\n\t\t\t\t\t\t\t\ttext="{info}"\r\n\t\t\t\t\t\t\t\ttype="{type}"\r\n\t\t\t\t\t\t\t\ttentative="{tentative}"></unified:CalendarAppointment></appointments><intervalHeaders><unified:CalendarAppointment\r\n\t\t\t\t\t\t\t\tstartDate="{start}"\r\n\t\t\t\t\t\t\t\tendDate="{end}"\r\n\t\t\t\t\t\t\t\ticon="{pic}"\r\n\t\t\t\t\t\t\t\ttitle="{title}"\r\n\t\t\t\t\t\t\t\ttype="{type}"></unified:CalendarAppointment></intervalHeaders></PlanningCalendarRow></rows></PlanningCalendar></content></Page></mvc:View>\r\n'
}});
